version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8082"  # Mappe le port 8082 du conteneur sur le port 8081 de la machine hôte
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/gymzdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - STRIPE_API_KEY=sk_test_dummy_key_for_testing_only
      - JWT_SECRET=your_jwt_secret_key_for_testing_use_a_strong_key_in_production
      - TWILIO_ACCOUNT_SID=dummy_twilio_sid_for_testing
      - TWILIO_AUTH_TOKEN=dummy_twilio_token_for_testing
      - TWILIO_PHONE_NUMBER=+12345678900
    depends_on:
      - db  # S'assure que le service db est démarré avant l'application
    networks:
      - gymz-network
    restart: on-failure  # Redémarre le service en cas de plantage

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gymzdb
    ports:
      - "3306:3306"  # Mappe le port 3306 du conteneur sur le port 3306 de la machine hôte
    volumes:
      - mysql-data:/var/lib/mysql  # Persiste les données de la base de données
    networks:
      - gymz-network

# Définition des réseaux et volumes
networks:
  gymz-network:
    driver: bridge

volumes:
  mysql-data:
